### ISSUE TITLE
Help me bro please 🙏🥺

### ISSUE THREAD

**Issue by Eugenexjay** [SHivnaTH13/Termux-OpenJDK#4]
==> Can you help me how to install java openjdk8 version "1.8.0_152" in termux because I really need to install it for APK builder I hope you can help me bro

[!!!] Like this
![Screenshot_20231220-210302.png](https://github.com/SHivnaTH13/Termux-OpenJDK/assets/120492432/512b8f3c-9c56-481f-a70e-bfaa66148841)

[!] Because your version of java openjdk8 does not work in APK builder in termux. it really needs that version of java "1.8.0_152"

==============================

[Step 1] ==> Download the APK file success.
![Screenshot_20231220-235401.png](https://github.com/SHivnaTH13/Termux-OpenJDK/assets/120492432/03340da3-4dab-4b27-9f7c-10313e2bb78b)
[Step 2] ==> But when I install the APK file there is an error. I'm done seeing that it's the wrong version of java so I've installed it so there's an error installing the apk file on the android phone!
![Screenshot_20231220-235558.png](https://github.com/SHivnaTH13/Termux-OpenJDK/assets/120492432/ea8b3615-fe50-4455-b15b-06244b592ee3)

==============================

[!] I searched everywhere to install the java openjdk version "1.8.0_152" in termux. But I still can't find anyone who teaches how to install it. please help me bro

**Comment by SHivnaTH13** [comment]
You can use one of this Android app to build Android app on Android
1. AndroidIDE for Android
2. Cosmic IDE
3. CodeAssist
4. AIDE
